---
- hosts: linux
  ignore_errors: yes
  tasks:
  - name: print std output
    shell: ls -l deb.txt
    register: output
  - debug: msg="standard output={{output.stdout}}"
  - debug: msg="standard error={{output.stderr}}"
